In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

In [3]:
df = pd.read_csv('insurance.csv')

In [4]:
df.sample(5)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
81,41,82.6,1.61,22.19,True,Mysore,freelancer,High
9,58,74.4,1.73,43.07,False,Pune,business_owner,Low
24,50,54.2,1.66,18.60,False,Mysore,private_job,Medium
83,61,83.3,1.85,2.16,True,Kota,retired,High
57,72,76.8,1.69,1.36,True,Jalandhar,retired,High

In [5]:
df['occupation'].unique()

<ArrowStringArray>
[       'retired',     'freelancer',        'student', 'government_job',
 'business_owner',     'unemployed',    'private_job']
Length: 7, dtype: str

In [6]:
df_feat=df.copy()

In [10]:
# Feature 1: BMI
df_feat['bmi']=df_feat['weight']/(df_feat['height']**2)

In [8]:
# Feature 2: Age Group
def age_group(age):
    if age < 25:
        return "young"
    elif age < 45:
        return "adult"
    elif age < 60:
        return "middle_aged"
    return "senior"

In [11]:
df_feat["age_group"] = df_feat["age"].apply(age_group)

In [16]:
# Feature 3: Lifestyle Risk
def lifestyle_risk(row):
    if row["smoker"] and row["bmi"] > 30:
        return "high"
    elif row["smoker"] or row["bmi"] > 27:
        return "medium"
    else:
        return "low"

In [17]:
df_feat["lifestyle_risk"] = df_feat.apply(lifestyle_risk, axis=1)

In [18]:

tier_1_cities = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"]
tier_2_cities = [
    "Jaipur", "Chandigarh", "Indore", "Lucknow", "Patna", "Ranchi", "Visakhapatnam", "Coimbatore",
    "Bhopal", "Nagpur", "Vadodara", "Surat", "Rajkot", "Jodhpur", "Raipur", "Amritsar", "Varanasi",
    "Agra", "Dehradun", "Mysore", "Jabalpur", "Guwahati", "Thiruvananthapuram", "Ludhiana", "Nashik",
    "Allahabad", "Udaipur", "Aurangabad", "Hubli", "Belgaum", "Salem", "Vijayawada", "Tiruchirappalli",
    "Bhavnagar", "Gwalior", "Dhanbad", "Bareilly", "Aligarh", "Gaya", "Kozhikode", "Warangal",
    "Kolhapur", "Bilaspur", "Jalandhar", "Noida", "Guntur", "Asansol", "Siliguri"
]

In [20]:
# Feature 4: City Tier
def city_tier(city):
    if city in tier_1_cities:
        return 1
    elif city in tier_2_cities:
        return 2
    else:
        return 3

In [23]:
df_feat['city_tier']=df_feat['city'].apply(city_tier)

In [24]:
df_feat.drop(columns=['age', 'weight', 'height', 'smoker', 'city'])[['income_lpa', 'occupation', 'bmi', 'age_group', 'lifestyle_risk', 'city_tier', 'insurance_premium_category']].sample(5)

,income_lpa,occupation,bmi,age_group,lifestyle_risk,city_tier,insurance_premium_category
87,25.59837,government_job,32.031250,adult,medium,1,Low
98,28.30000,business_owner,30.521676,adult,medium,1,Low
68,0.68000,student,22.963196,young,low,2,Low
26,23.61000,freelancer,30.477219,adult,medium,2,Medium
40,40.19000,unemployed,24.349609,adult,medium,1,Medium

In [25]:
import os
print(os.getcwd())

C:\Users\Riya Gupta\Insurance Premium Predictor